import NavBar from "@/components/NavBar"
import PageFooter from "@/components/PageFooter"
import styles from "./styles.module.css";
import { AuthProvider } from "@/providers/AuthProvider";
import { RegisterProvider } from "@/providers/RegisterAuth";
import { BookProvider } from "@/providers/BookProvider";
import { BookRequestProvider } from "@/providers/BookRequestProvider";
import { UserProvider } from "@/providers/UserProvider";

export const metadata = {
  title: 'Readers Emporium',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) :React.ReactNode{
  

  return (
    <AuthProvider>
      <RegisterProvider>
        <BookProvider>
          <BookRequestProvider>
            <UserProvider>
              <html lang="en">
                <body className={styles.body}>
                  {children}
                  
                </body>
              </html>
            </UserProvider>
          </BookRequestProvider>
        </BookProvider>
      </RegisterProvider>
    </AuthProvider>
    
  )
}
