import NavBar from "@/components/NavBar"
import PageFooter from "@/components/PageFooter"
import styles from "./styles.module.css";

export const metadata = {
  title: 'Readers Emporium',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) :React.ReactNode{

  return (
    <html lang="en">
      <body className={styles.body}>
        <NavBar/>
        {children}
        <PageFooter/>
      </body>
    </html>
  )
}
